// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/buyers": {
            "get": {
                "description": "Devuelve todos los buyers del sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buyer"
                ],
                "summary": "Devuelve todos los buyers",
                "responses": {
                    "200": {
                        "description": "Lista de buyers obtenida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerListResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo buyer en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buyer"
                ],
                "summary": "Crea un nuevo buyer",
                "parameters": [
                    {
                        "description": "Buyer a crear",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Buyer creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerDoc"
                        }
                    },
                    "409": {
                        "description": "Código del buyer ya existente",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/buyers/reportPurchaseOrders": {
            "get": {
                "description": "Devuelve un reporte de órdenes de compra por Buyer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buyer"
                ],
                "summary": "Reporte de órdenes de compra por Buyer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del buyer",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reporte de órdenes de compra obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerPurchaseOrdersReportResponse"
                        }
                    },
                    "400": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Buyer no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/buyers/{id}": {
            "get": {
                "description": "Devuelve un buyer por id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buyer"
                ],
                "summary": "Devuelve un buyer por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del buyer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Buyer obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerResponse"
                        }
                    },
                    "400": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Buyer no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un buyer por id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buyer"
                ],
                "summary": "Elimina un buyer por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del buyer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Buyer eliminado exitosamente"
                    },
                    "400": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Buyer no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza un buyer por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buyer"
                ],
                "summary": "Actualiza un buyer por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del buyer",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Buyer a actualizar",
                        "name": "buyer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerAttributes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Buyer actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.BuyerResponse"
                        }
                    },
                    "400": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Buyer no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Código del buyer ya existente",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/carries": {
            "post": {
                "description": "Crea un nuevo carry en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Carries"
                ],
                "summary": "Crea un nuevo carry",
                "parameters": [
                    {
                        "description": "Datos del carry",
                        "name": "carries",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CarriesDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Carry creado",
                        "schema": {
                            "$ref": "#/definitions/domain.CarryResponse"
                        }
                    },
                    "409": {
                        "description": "Carry ya existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employee/reportInboundOrders": {
            "get": {
                "description": "Reporte de inbound orders por empleado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Reporte de inbound orders por empleado",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la sección",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reporte de inbound orders por empleado",
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeeWithInboundOrdersCountResponse"
                        }
                    },
                    "400": {
                        "description": "ID malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El empleado no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employees": {
            "get": {
                "description": "Retorna una lista de todos los Employees registrados en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Lista todos los Employees",
                "responses": {
                    "200": {
                        "description": "Listado de Employees",
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeesResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo empleado en el sistema con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Crea un nuevo empleado",
                "parameters": [
                    {
                        "description": "Datos del empleado a crear",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeeAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Empleado creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeeResponse"
                        }
                    },
                    "409": {
                        "description": "El código de tarjeta ya existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "get": {
                "description": "Retorna la información de un Employee por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Retorna un Employee por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Employee",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Listado de Employees",
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeesResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El employee no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un employee por su ID de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Elimina un employee por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del employee",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "employee eliminado exitosamente"
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El employee no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza los datos de un empleado existente en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee"
                ],
                "summary": "Actualiza un empleado por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del empleado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del empleado a actualizar",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeeAttributes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Empleado actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.EmployeeResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El empleado no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "El código de tarjeta ya existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inboundOrders": {
            "post": {
                "description": "Crea un nuevo inbound en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "InboundOrder"
                ],
                "summary": "Crea un nuevo inbound order",
                "parameters": [
                    {
                        "description": "inbound order a crear",
                        "name": "InboundOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.InboundOrderAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Inbound Order creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.InboundOrderResponse"
                        }
                    },
                    "409": {
                        "description": "Conflicto de clave foránea o unica",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/productBatches": {
            "post": {
                "description": "Crea un nuevo product batch en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductBatch"
                ],
                "summary": "Crea un nuevo product batch",
                "parameters": [
                    {
                        "description": "product batch a crear",
                        "name": "productBatch",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProductBatchAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Product Batch creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductBatchResponse"
                        }
                    },
                    "409": {
                        "description": "Conflicto de clave foránea o unica",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/productRecords": {
            "get": {
                "description": "Devuelve todos los reportes de productos y filtra por id de producto",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ProductRecord"
                ],
                "summary": "Devuelve todos los reportes de productos y filtra por id de producto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de reportes obtenida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.ReportResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Retorna una lista de todos los productos registrados en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Lista todos los productos",
                "responses": {
                    "200": {
                        "description": "Listado de productos",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductsResponse"
                        }
                    },
                    "400": {
                        "description": "Error al parsear la fecha de caducidad",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Productos no encontrados",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo producto en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Crea un nuevo producto",
                "parameters": [
                    {
                        "description": "Producto a crear",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProductAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Producto creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductResponse"
                        }
                    },
                    "409": {
                        "description": "Tipo de producto o vendedor no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Obtiene un producto por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Obtiene un producto por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Producto encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "ID de producto inválido",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Producto no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un producto por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Elimina un producto por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Producto eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "ID de producto inválido",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Producto no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Error de eliminación por clave foránea",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza un producto por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Actualiza un producto por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Producto a actualizar",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProductAttributes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Producto actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "ID de producto inválido",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Producto no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflicto de producto",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Error de validación",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/purchaseOrders": {
            "post": {
                "description": "Crea una nueva orden de compra en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PurchaseOrders"
                ],
                "summary": "Crea una nueva orden de compra",
                "parameters": [
                    {
                        "description": "Datos de la orden de compra a crear",
                        "name": "purchase_order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PurchaseOrderAttributesSwagger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Orden de compra creada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.PurchaseOrderResponse"
                        }
                    },
                    "409": {
                        "description": "El número de orden ya existe, o buyer/product no existen",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sections": {
            "get": {
                "description": "Retorna una lista con todas las sections registradas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Section"
                ],
                "summary": "Lista todas las sections",
                "responses": {
                    "200": {
                        "description": "Listado de sections",
                        "schema": {
                            "$ref": "#/definitions/domain.SectionsResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo section en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Section"
                ],
                "summary": "Crea un nuevo section",
                "parameters": [
                    {
                        "description": "section a crear",
                        "name": "section",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SectionAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Section creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.SectionResponse"
                        }
                    },
                    "409": {
                        "description": "Código del section ya existente",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sections/reportProducts": {
            "get": {
                "description": "Reporte de productos por sección",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Section"
                ],
                "summary": "Reporte de productos por sección",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la sección",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reporte de productos por sección",
                        "schema": {
                            "$ref": "#/definitions/domain.SectionWithProductsCountResponse"
                        }
                    },
                    "400": {
                        "description": "ID malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "La sección no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sections/{id}": {
            "get": {
                "description": "Retorna la información de un section por su id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Section"
                ],
                "summary": "Retorna un section por su id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del section",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Section encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.SectionResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Section no encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina una sección por su ID de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Section"
                ],
                "summary": "Elimina una sección por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la sección",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "sección eliminada exitosamente"
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "La sección no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza una sección por su ID de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Section"
                ],
                "summary": "Actualiza una sección por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la sección",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "sección a actualizar",
                        "name": "section",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SectionAttributes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sección actualizada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.SectionResponse"
                        }
                    },
                    "404": {
                        "description": "La sección no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sellers": {
            "get": {
                "description": "Retorna una lista de todos los proveedores registrados en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sellers"
                ],
                "summary": "Lista todos los proveedores",
                "responses": {
                    "200": {
                        "description": "Listado de proveedores",
                        "schema": {
                            "$ref": "#/definitions/domain.SellersResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo proveedor en el sistema con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sellers"
                ],
                "summary": "Crea un nuevo proveedor",
                "parameters": [
                    {
                        "description": "Datos del proveedor a crear",
                        "name": "seller",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SellerAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Proveedor creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.SellerResponse"
                        }
                    },
                    "409": {
                        "description": "El CID ya existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sellers/{id}": {
            "get": {
                "description": "Retorna la información de un proveedor específico basado en su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sellers"
                ],
                "summary": "Retorna un proveedor por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del proveedor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proveedor encontrado",
                        "schema": {
                            "$ref": "#/definitions/domain.SellerResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El proveedor no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un proveedor existente de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sellers"
                ],
                "summary": "Elimina un proveedor por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del proveedor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Proveedor eliminado exitosamente"
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El proveedor no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza un proveedor existente con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sellers"
                ],
                "summary": "Actualiza un proveedor por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del proveedor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del proveedor a actualizar",
                        "name": "seller",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SellerAttributes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proveedor actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.SellerResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El proveedor no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "El CID ya existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/warehouses": {
            "get": {
                "description": "Retorna una lista de todos los warehouses registrados en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warehouse"
                ],
                "summary": "Lista todos los warehouses",
                "responses": {
                    "200": {
                        "description": "Listado de warehouses",
                        "schema": {
                            "$ref": "#/definitions/domain.WarehousesResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo warehouse en el sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warehouse"
                ],
                "summary": "Crea un nuevo warehouse",
                "parameters": [
                    {
                        "description": "warehouse a crear",
                        "name": "warehouse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.WarehouseAttributes"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Warehouse creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.WarehouseResponse"
                        }
                    },
                    "409": {
                        "description": "Código del warehouse ya existente",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Datos malformados o faltantes",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/warehouses/{id}": {
            "get": {
                "description": "Retorna la información de un warehouse por su ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warehouse"
                ],
                "summary": "Retorna un warehouse por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del warehouse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Listado de warehouses",
                        "schema": {
                            "$ref": "#/definitions/domain.WarehousesResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El warehouse no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un warehouse por su ID de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warehouse"
                ],
                "summary": "Elimina un warehouse por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del warehouse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "warehouse eliminado exitosamente"
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El warehouse no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza un warehouse por su ID de la base de datos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Warehouse"
                ],
                "summary": "Actualiza un warehouse por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del warehouse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "warehouse a actualizar",
                        "name": "warehouse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.WarehouseAttributes"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "warehouse actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.WarehouseResponse"
                        }
                    },
                    "400": {
                        "description": "ID no enviado o malformado",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "El warehouse no existe",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Código del warehouse ya existente",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.BuyerAttributes": {
            "type": "object",
            "properties": {
                "card_number_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "domain.BuyerDoc": {
            "type": "object",
            "properties": {
                "card_number_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "domain.BuyerListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.BuyerDoc"
                    }
                }
            }
        },
        "domain.BuyerPurchaseOrdersReport": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "integer"
                },
                "card_number_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "purchase_orders_count": {
                    "type": "integer"
                }
            }
        },
        "domain.BuyerPurchaseOrdersReportResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.BuyerPurchaseOrdersReport"
                    }
                }
            }
        },
        "domain.BuyerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.BuyerDoc"
                }
            }
        },
        "domain.CarriesDoc": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cid": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locality_id": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "domain.CarryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.CarriesDoc"
                }
            }
        },
        "domain.EmployeeAttributes": {
            "type": "object",
            "properties": {
                "card_number_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.EmployeeDoc": {
            "type": "object",
            "properties": {
                "card_number_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.EmployeeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.EmployeeDoc"
                }
            }
        },
        "domain.EmployeeWithInboundOrdersCount": {
            "type": "object",
            "properties": {
                "card_number_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "inbound_orders_count": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.EmployeeWithInboundOrdersCountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.EmployeeWithInboundOrdersCount"
                    }
                }
            }
        },
        "domain.EmployeesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.EmployeeDoc"
                    }
                }
            }
        },
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.InboundOrderAttributes": {
            "type": "object",
            "properties": {
                "employee_id": {
                    "type": "integer"
                },
                "order_date": {
                    "$ref": "#/definitions/utils.Date"
                },
                "order_number": {
                    "type": "string"
                },
                "product_batch_id": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.InboundOrderDoc": {
            "type": "object",
            "properties": {
                "employee_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "order_date": {
                    "$ref": "#/definitions/utils.Date"
                },
                "order_number": {
                    "type": "string"
                },
                "product_batch_id": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.InboundOrderResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.InboundOrderDoc"
                }
            }
        },
        "domain.ProductAttributes": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "expiration_rate": {
                    "type": "number"
                },
                "freezing_rate": {
                    "type": "number"
                },
                "height": {
                    "type": "number"
                },
                "length": {
                    "type": "number"
                },
                "netweight": {
                    "type": "number"
                },
                "product_code": {
                    "type": "string"
                },
                "product_type_id": {
                    "type": "integer"
                },
                "recommended_freezing_temperature": {
                    "type": "number"
                },
                "seller_id": {
                    "type": "integer"
                },
                "width": {
                    "type": "number"
                }
            }
        },
        "domain.ProductBatchAttributes": {
            "type": "object",
            "properties": {
                "batch_number": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "integer"
                },
                "current_temperature": {
                    "type": "number"
                },
                "due_date": {
                    "$ref": "#/definitions/utils.Date"
                },
                "initial_quantity": {
                    "type": "integer"
                },
                "manufacturing_date": {
                    "$ref": "#/definitions/utils.Date"
                },
                "manufacturing_hour": {
                    "type": "integer"
                },
                "minimum_temperature": {
                    "type": "number"
                },
                "product_id": {
                    "type": "integer"
                },
                "section_id": {
                    "type": "integer"
                }
            }
        },
        "domain.ProductBatchDoc": {
            "type": "object",
            "properties": {
                "batch_number": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "integer"
                },
                "current_temperature": {
                    "type": "number"
                },
                "due_date": {
                    "$ref": "#/definitions/utils.Date"
                },
                "id": {
                    "type": "integer"
                },
                "initial_quantity": {
                    "type": "integer"
                },
                "manufacturing_date": {
                    "$ref": "#/definitions/utils.Date"
                },
                "manufacturing_hour": {
                    "type": "integer"
                },
                "minimum_temperature": {
                    "type": "number"
                },
                "product_id": {
                    "type": "integer"
                },
                "section_id": {
                    "type": "integer"
                }
            }
        },
        "domain.ProductBatchResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.ProductBatchDoc"
                }
            }
        },
        "domain.ProductDoc": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "expiration_rate": {
                    "type": "number"
                },
                "freezing_rate": {
                    "type": "number"
                },
                "height": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "length": {
                    "type": "number"
                },
                "netweight": {
                    "type": "number"
                },
                "product_code": {
                    "type": "string"
                },
                "product_type_id": {
                    "type": "integer"
                },
                "recommended_freezing_temperature": {
                    "type": "number"
                },
                "seller_id": {
                    "type": "integer"
                },
                "width": {
                    "type": "number"
                }
            }
        },
        "domain.ProductResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.ProductDoc"
                }
            }
        },
        "domain.ProductsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ProductDoc"
                    }
                }
            }
        },
        "domain.PurchaseOrderAttributesSwagger": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "integer",
                    "example": 1
                },
                "order_date": {
                    "type": "string",
                    "example": "2021-04-04"
                },
                "order_number": {
                    "type": "string",
                    "example": "order#1"
                },
                "product_record_id": {
                    "type": "integer",
                    "example": 1
                },
                "tracking_code": {
                    "type": "string",
                    "example": "abscf123"
                }
            }
        },
        "domain.PurchaseOrderDoc": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "order_date": {
                    "type": "string"
                },
                "order_number": {
                    "type": "string"
                },
                "product_record_id": {
                    "type": "integer"
                },
                "tracking_code": {
                    "type": "string"
                }
            }
        },
        "domain.PurchaseOrderResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.PurchaseOrderDoc"
                }
            }
        },
        "domain.ReportProductRecord": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "records_count": {
                    "type": "integer"
                }
            }
        },
        "domain.ReportResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ReportProductRecord"
                    }
                }
            }
        },
        "domain.SectionAttributes": {
            "type": "object",
            "properties": {
                "current_capacity": {
                    "type": "integer"
                },
                "current_temperature": {
                    "type": "number"
                },
                "maximum_capacity": {
                    "type": "integer"
                },
                "minimum_capacity": {
                    "type": "integer"
                },
                "minimum_temperature": {
                    "type": "number"
                },
                "product_type_id": {
                    "type": "integer"
                },
                "section_number": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.SectionDoc": {
            "type": "object",
            "properties": {
                "current_capacity": {
                    "type": "integer"
                },
                "current_temperature": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "maximum_capacity": {
                    "type": "integer"
                },
                "minimum_capacity": {
                    "type": "integer"
                },
                "minimum_temperature": {
                    "type": "number"
                },
                "product_type_id": {
                    "type": "integer"
                },
                "section_number": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "integer"
                }
            }
        },
        "domain.SectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.SectionDoc"
                }
            }
        },
        "domain.SectionWithProductCount": {
            "type": "object",
            "properties": {
                "product_count": {
                    "type": "integer"
                },
                "section_id": {
                    "type": "integer"
                },
                "section_number": {
                    "type": "string"
                }
            }
        },
        "domain.SectionWithProductsCountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SectionWithProductCount"
                    }
                }
            }
        },
        "domain.SectionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SectionDoc"
                    }
                }
            }
        },
        "domain.SellerAttributes": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cid": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "locality_id": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "domain.SellerDoc": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "cid": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locality_id": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "domain.SellerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.SellerDoc"
                }
            }
        },
        "domain.SellersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SellerDoc"
                    }
                }
            }
        },
        "domain.WarehouseAttributes": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "locality_id": {
                    "type": "string"
                },
                "minimun_capacity": {
                    "type": "integer"
                },
                "minimun_temperature": {
                    "type": "number"
                },
                "telephone": {
                    "type": "string"
                },
                "warehouse_code": {
                    "type": "string"
                }
            }
        },
        "domain.WarehouseDoc": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locality_id": {
                    "type": "string"
                },
                "minimun_capacity": {
                    "type": "integer"
                },
                "minimun_temperature": {
                    "type": "number"
                },
                "telephone": {
                    "type": "string"
                },
                "warehouse_code": {
                    "type": "string"
                }
            }
        },
        "domain.WarehouseResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.WarehouseDoc"
                }
            }
        },
        "domain.WarehousesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.WarehouseDoc"
                    }
                }
            }
        },
        "utils.Date": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API de Sellers y Warehouses",
	Description:      "API para gestionar sellers y warehouses",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
